[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Nicolas Kivelä <nicolas.kivela@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
sqlalchemy = "^2.0.43"
python-multipart = "^0.0.20"
python-dotenv = "^1.1.1"
litellm = "^1.77.7"
pdfplumber = "^0.11.7"
python-docx = "^1.2.0"
google-generativeai = "^0.8.5"
bs4 = "^0.0.2"
playwright = "^1.55.0"
sqlmodel = "^0.0.27"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
